apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-demo
  namespace: fastapi-demo
  labels:
    app: fastapi-demo
data:
  # Here we define the environment variables that will be used by the container
  # in the deployment. These variables will be available to the container as
  # environment variables.
  DEBUG_MODE: "True"