apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastapi-demo
labels:
  - pairs:
      app: fastapi-demo
    includeSelectors: true
nameSuffix: -dev
images:
  - name: efraintorlo/fastapi-demo
    newTag: af97f1a
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - ingress.yaml
